#!/usr/bin/env python3.9

# read instruction file
# 

import os
import re
import sys

args=sys.argv
if(len(args) < 2):
    print('\nyou need argument\n')
    sys.exit()

instruction_file = args[1]

if(not os.path.isfile(instruction_file)):
    print('\nfile does not exist\n')
    sys.exit()

f = open(instruction_file, 'r')
lines = f.read().splitlines()
lines.reverse()
f.close()

dir=''

instructions = []
instruction  = {}

for line in lines:
    line = line.strip()
    if(line.startswith('dir:')):
        dir = line.replace('dir:', '').strip()
    if(re.match('(file|key|ofs|text):', line)):
        k, v = [x.strip() for x in line.split(':')]
        instruction[k] = v
        if(k == 'file'):
            instructions.append(instruction)
            instruction = {}

for instruction in instructions:
    file = instruction['file']
    ofs  = int(instruction['ofs'])
    key  = instruction['key']
    text = instruction['text']
    f = open(os.path.join(dir, file), 'r')
    lines = f.read().splitlines()
    lines_copy = []
    count = -1 
    for line in lines:
        lines_copy.append(line)
        if(line.strip().startswith(key.strip())):
            count = 0
        if(count > -1):
           count = count + 1
           if(count == ofs):
             lines_copy.append(text)
             count = -1

    f.close()
    f = open(os.path.join(dir, file), 'w')
    f.write('\n'.join(lines_copy)[:-1])
    f.close()
